TINY_FONT = ("Arial", 6)
TINY_BOLD_FONT = ("Arial Bold", 6)
SMALL_FONT = ("Arial", 8)
MEDIUM_FONT = ("Arial Regular", 12)
LARGE_FONT = ("Arial Bold", 16)
OMEGA_FONT = ("Arial Bold", 32)

DANGER_COLOUR = "#F28BA8"
ACCENT_COLOUR = "#89B4FA"
ALTERNATE_DARK_COLOUR = "#181825"
DEFAULT_COLOUR = "#1E1E2E"
TEXT_COLOUR = "#CDD5F4"

PADDING_LARGE = 5
PADDING_SMALL = 2

UI_SCALE = 1.35
CONFIG_PATH = "./config.json"
WINDOW_SIZE = {"x": 1280, "y": 720}
